// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deck.sql

package deck

import (
	"context"

	"github.com/google/uuid"
)

const checkReadPermission = `-- name: CheckReadPermission :one
select exists (
        select 1
        from deck_user du
            inner join deck d on d.id = du.deck_id
        where d.visibility = 'public'
            or (
                du.user_id = $1
                and du.deck_id = $2
            )
    ) as row_exists
`

type CheckReadPermissionParams struct {
	UserID string    `json:"userId"`
	DeckID uuid.UUID `json:"deckId"`
}

func (q *Queries) CheckReadPermission(ctx context.Context, arg CheckReadPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkReadPermission, arg.UserID, arg.DeckID)
	var row_exists bool
	err := row.Scan(&row_exists)
	return row_exists, err
}

const checkWritePermission = `-- name: CheckWritePermission :one
select exists (
        select 1
        from deck_user du
        where du.user_id = $1
            and du.deck_id = $2
    ) as row_exists
`

type CheckWritePermissionParams struct {
	UserID string    `json:"userId"`
	DeckID uuid.UUID `json:"deckId"`
}

func (q *Queries) CheckWritePermission(ctx context.Context, arg CheckWritePermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkWritePermission, arg.UserID, arg.DeckID)
	var row_exists bool
	err := row.Scan(&row_exists)
	return row_exists, err
}

const create = `-- name: Create :one
insert into deck (name, description, thumbnail, visibility)
values($1, $2, $3, $4)
returning id, name, description, thumbnail, visibility, archived_at, created_at, updated_at
`

type CreateParams struct {
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	Thumbnail   *string        `json:"thumbnail"`
	Visibility  DeckVisibility `json:"visibility"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Deck, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.Description,
		arg.Thumbnail,
		arg.Visibility,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPermitted = `-- name: FindPermitted :one
select d.id, d.name, d.description, d.thumbnail, d.visibility, d.archived_at, d.created_at, d.updated_at
from deck d
    left join deck_user du on d.id = du.deck_id
where d.id = $1
    and (
        d.visibility::text = 'public'
        or du.user_id = $2
    )
`

type FindPermittedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) FindPermitted(ctx context.Context, arg FindPermittedParams) (Deck, error) {
	row := q.db.QueryRow(ctx, findPermitted, arg.ID, arg.UserID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const get = `-- name: Get :one
select id, name, description, thumbnail, visibility, archived_at, created_at, updated_at
from deck
where id = $2
    and exists (
        select 1
        from deck_user
        where user_id = $1
            and deck_id = $2
    )
`

type GetParams struct {
	UserID string    `json:"userId"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) Get(ctx context.Context, arg GetParams) (Deck, error) {
	row := q.db.QueryRow(ctx, get, arg.UserID, arg.ID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkUser = `-- name: LinkUser :exec
insert into deck_user(deck_id, user_id, role)
values($1, $2, 'admin')
`

type LinkUserParams struct {
	DeckID uuid.UUID `json:"deckId"`
	UserID string    `json:"userId"`
}

func (q *Queries) LinkUser(ctx context.Context, arg LinkUserParams) error {
	_, err := q.db.Exec(ctx, linkUser, arg.DeckID, arg.UserID)
	return err
}

const listPermitted = `-- name: ListPermitted :many
select d.id, d.name, d.description, d.thumbnail, d.visibility, d.archived_at, d.created_at, d.updated_at
from deck d
    inner join deck_user du on d.id = du.deck_id
where du.user_id = $1
    and (
        $4::text is null
        or d.name ILIKE '%' || $4 || '%'
    )
    and (
        $5::text is null
        or d.description ILIKE '%' || $5 || '%'
    )
    and (
        $6::boolean is true
        or d.archived_at is null
    )
    and (
        $7::text is null
        or d.visibility::text = $7
    )
order by d.created_at desc,
    d.id asc
limit $2 offset $3
`

type ListPermittedParams struct {
	UserID      string  `json:"userId"`
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Archived    *bool   `json:"archived"`
	Visibility  *string `json:"visibility"`
}

func (q *Queries) ListPermitted(ctx context.Context, arg ListPermittedParams) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listPermitted,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Name,
		arg.Description,
		arg.Archived,
		arg.Visibility,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Visibility,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permittedCount = `-- name: PermittedCount :one
select count(d.id) as total_count
from deck d
    inner join deck_user du on d.id = du.deck_id
where du.user_id = $1
    and (
        $2::text is null
        or d.name ILIKE '%' || $2 || '%'
    )
    and (
        $3::text is null
        or d.description ILIKE '%' || $3 || '%'
    )
    and (
        $4::boolean is true
        or d.archived_at is null
    )
    and (
        $5::text is null
        or d.visibility::text = $5
    )
`

type PermittedCountParams struct {
	UserID      string  `json:"userId"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Archived    *bool   `json:"archived"`
	Visibility  *string `json:"visibility"`
}

func (q *Queries) PermittedCount(ctx context.Context, arg PermittedCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, permittedCount,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Archived,
		arg.Visibility,
	)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const update = `-- name: Update :one
update deck d
set name = COALESCE($3, name),
    description = COALESCE($4, description),
    thumbnail = COALESCE($5, thumbnail),
    visibility = COALESCE(
        $6,
        visibility
    ),
    updated_at = NOW()
FROM deck_user du
WHERE d.id = du.deck_id
    AND du.user_id = $1
    AND d.id = $2
returning d.id, d.name, d.description, d.thumbnail, d.visibility, d.archived_at, d.created_at, d.updated_at
`

type UpdateParams struct {
	UserID      string             `json:"userId"`
	ID          uuid.UUID          `json:"id"`
	Name        *string            `json:"name"`
	Description *string            `json:"description"`
	Thumbnail   *string            `json:"thumbnail"`
	Visibility  NullDeckVisibility `json:"visibility"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Deck, error) {
	row := q.db.QueryRow(ctx, update,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Thumbnail,
		arg.Visibility,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
