// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package deck

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeckUserRole string

const (
	DeckUserRoleMember DeckUserRole = "member"
	DeckUserRoleAdmin  DeckUserRole = "admin"
)

func (e *DeckUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeckUserRole(s)
	case string:
		*e = DeckUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for DeckUserRole: %T", src)
	}
	return nil
}

type NullDeckUserRole struct {
	DeckUserRole DeckUserRole `json:"deckUserRole"`
	Valid        bool         `json:"valid"` // Valid is true if DeckUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeckUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.DeckUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeckUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeckUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeckUserRole), nil
}

type DeckVisibility string

const (
	DeckVisibilityPublic  DeckVisibility = "public"
	DeckVisibilityPrivate DeckVisibility = "private"
)

func (e *DeckVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeckVisibility(s)
	case string:
		*e = DeckVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for DeckVisibility: %T", src)
	}
	return nil
}

type NullDeckVisibility struct {
	DeckVisibility DeckVisibility `json:"deckVisibility"`
	Valid          bool           `json:"valid"` // Valid is true if DeckVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeckVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.DeckVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeckVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeckVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeckVisibility), nil
}

type AuthAccount struct {
	ID                    string     `json:"id"`
	AccountId             string     `json:"accountId"`
	ProviderId            string     `json:"providerId"`
	UserId                string     `json:"userId"`
	AccessToken           *string    `json:"accessToken"`
	RefreshToken          *string    `json:"refreshToken"`
	IdToken               *string    `json:"idToken"`
	AccessTokenExpiresAt  *time.Time `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt *time.Time `json:"refreshTokenExpiresAt"`
	Scope                 *string    `json:"scope"`
	Password              *string    `json:"password"`
	CreatedAt             time.Time  `json:"createdAt"`
	UpdatedAt             time.Time  `json:"updatedAt"`
}

type AuthJwk struct {
	ID         string     `json:"id"`
	PublicKey  string     `json:"publicKey"`
	PrivateKey string     `json:"privateKey"`
	CreatedAt  time.Time  `json:"createdAt"`
	ExpiresAt  *time.Time `json:"expiresAt"`
}

type AuthSession struct {
	ID             string    `json:"id"`
	ExpiresAt      time.Time `json:"expiresAt"`
	Token          string    `json:"token"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	IpAddress      *string   `json:"ipAddress"`
	UserAgent      *string   `json:"userAgent"`
	UserId         string    `json:"userId"`
	ImpersonatedBy *string   `json:"impersonatedBy"`
}

type AuthUser struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Email           string     `json:"email"`
	EmailVerified   bool       `json:"emailVerified"`
	Image           *string    `json:"image"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	Username        *string    `json:"username"`
	DisplayUsername *string    `json:"displayUsername"`
	Role            *string    `json:"role"`
	Banned          *bool      `json:"banned"`
	BanReason       *string    `json:"banReason"`
	BanExpires      *time.Time `json:"banExpires"`
}

type AuthVerification struct {
	ID         string    `json:"id"`
	Identifier string    `json:"identifier"`
	Value      string    `json:"value"`
	ExpiresAt  time.Time `json:"expiresAt"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Card struct {
	ID          uuid.UUID   `json:"id"`
	DeckID      pgtype.UUID `json:"deckId"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Image       *string     `json:"image"`
	ArchivedAt  *time.Time  `json:"archivedAt"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   *time.Time  `json:"updatedAt"`
}

type Deck struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	Thumbnail   *string        `json:"thumbnail"`
	Visibility  DeckVisibility `json:"visibility"`
	ArchivedAt  *time.Time     `json:"archivedAt"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   *time.Time     `json:"updatedAt"`
}

type DeckUser struct {
	DeckID    uuid.UUID    `json:"deckId"`
	UserID    string       `json:"userId"`
	Role      DeckUserRole `json:"role"`
	CreatedAt time.Time    `json:"createdAt"`
}
